= SE Block Tools for Blender

Modelling blocks for http://www.spaceengineersgame.com/[Space Engineers] is a process that 
involves a lot of intermediary files and manual parametrization. 
This add-on simplifies the steps you need to take to get from a 3D mesh in Blender to 
Space Engineer's own `.mwm` mesh-format. To do that

. The add-on provides property panels for all the special data SE stores inside an `.mwm` file directly in Blender.
. You use Blender layers to define the main model, the collision model, mount-points, mirroring-settings,
  level-of-detail models and construction stages.
. The workflow that configures and runs the conversion-tools (Havok, MwmBuilder) for you is customizable
  to suite your needs.

The most current version is available in the
https://github.com/harag-on-steam/se-blender/releases/latest[release section] on GitHub.

The documentation is published to the project's http://harag-on-steam.github.io/se-blender/[Github pages].

= What's different in this branch?

* Added option for linking to an XML file containing your material names and the correct texture paths for those materials. Just leave the nodes blank in Blender and it'll automatically use the paths from your XML. 

Download Link (Zip file for easy installation)

https://github.com/khamseen/se-blender/raw/master/blender-space_engineers-0.7.0_khamedits.zip
