= SE Block Tools for Blender

Modelling blocks for Space Engineers is a process that involves a lot of intermediary files and manual parametrization.
This add-on eases the steps you need to take to get from a 3D mesh in Blender to Space Engineer's own .mwm mesh-format.
To do that it provides property panels for all the special data Space Engineers stores inside an .mwm file
directly in Blender.
In addition it is able to automatically configure and run the conversion-tools you would normally run by hand.

NOTE: The add-on (and this documentation) expect you to know how to work with Blender.
So if you are new to 3D modelling you should probably learn how to do that properly before you continue.

// TODO Having said that, there is an addendum that should help you to get on the right track.

include::parts/install.adoc[]

include::parts/workflow.adoc[]

include::parts/export.adoc[]

+++<link href="featherlight.min.css" type="text/css" rel="stylesheet" title="Featherlight Styles" />
<script src="jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="featherlight.min.js" type="text/javascript" charset="utf-8"></script>
<script>$( 'a[href$=".png"]' ).featherlight(); $( 'a[href="#blockdef"]' ).featherlight();</script>+++
